### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by robinjmurphy** [refactoring-by-example/refactoringbyexample.com#3]
😎

**Comment by robinjmurphy** [comment]
Been working on one idea at the moment. Let me know what you think @nspragg – any thoughts on a colour you'd like? I just chose the red on the website randomly so I've included a few different ones here.

### Masthead

<img width="1280" alt="logo-1 2x" src="https://cloud.githubusercontent.com/assets/917111/23360079/5717d798-fce1-11e6-9327-fec5034bb67d.png">

![masthead-fullpage](https://cloud.githubusercontent.com/assets/917111/23360186/f6721524-fce1-11e6-9649-c4ed8e1e84c1.png)


### Laptop sticker

<img width="1280" alt="logo-2 2x" src="https://cloud.githubusercontent.com/assets/917111/23360087/6111e46e-fce1-11e6-9007-269a25f2236c.png">

<img width="1280" alt="logo-3 2x" src="https://cloud.githubusercontent.com/assets/917111/23360091/65423fe8-fce1-11e6-8600-6245a7fbfc23.png">

<img width="1280" alt="logo-4 2x" src="https://cloud.githubusercontent.com/assets/917111/23360093/6899a0b4-fce1-11e6-8226-368efc1e64c1.png">

<img width="1280" alt="logo-5 2x" src="https://cloud.githubusercontent.com/assets/917111/23360096/6b38b45e-fce1-11e6-9274-77734fd4ae9c.png">

### Logo

<img width="1280" alt="logo-6 2x" src="https://cloud.githubusercontent.com/assets/917111/23360100/6df34ea2-fce1-11e6-9120-baf92b8d80fe.png">

**Comment by nspragg** [comment]
Red for me 💯

**Comment by robinjmurphy** [comment]
Cool. I'll put together some screenshots using the red.
